trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: docker pull katalonstudio/katalon:6.3.3
  displayName: 'Pull katalon studio images'
- script: docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon:6.3.3 katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/signup_monitoring"
  displayName: 'Runnning Katalon TS_RegressionTest'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/